# Generated by Django 5.1.5 on 2025-05-10 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bengalurujobs',
            new_name='Bengjobs',
        ),
        migrations.RenameModel(
            old_name='Hyderabadjobs',
            new_name='Deljobs',
        ),
        migrations.RenameModel(
            old_name='Delhijobs',
            new_name='Hydjobs',
        ),
    ]
